'use strict';
const groups={evidence:['100%','guaranteed','scientifically proven','no doubt','the truth is','will cure'],context:['always','never','everyone must','all women','all men','the only way'],pressure:['act now','last chance','today only','limited seats','buy now','enroll'],authority:['experts agree','science says','research proves','secret method','insiders know'],identity:['real mothers','good parents','awake women','real men','if you cared','only losers'],zero:['choose yourself or','versus','partner is the enemy','one side must lose'],sealing:['if you disagree it proves','critics are afraid','only closed-minded people','you will understand after you buy'],hazard:['stop your medication','ignore your doctor','invest everything','borrow money','share their address','quit immediately'],distress:['sad','angry','afraid','hopeless','hurt','exhausted','overwhelmed','depressed']};
const score=(txt,list)=>Math.min(1,list.filter(x=>txt.toLowerCase().includes(x)).length/2);
const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let repair='';
async function load(){const x=await chrome.storage.session.get(['verityweaveSelection','verityweaveSourceUrl','verityweaveCapturedAt']);text.value=x.verityweaveSelection||'';source.textContent=x.verityweaveSourceUrl?`Captured from ${x.verityweaveSourceUrl} at ${x.verityweaveCapturedAt||''}`:'No source URL was captured.';if(text.value)analyze.click()}
analyze.onclick=()=>{const t=text.value.trim();if(!t){result.innerHTML='<p class="muted">Paste or select text first.</p>';return}const s={evidence_deficit:score(t,groups.evidence),context_compression:score(t,groups.context),commercial_pressure:score(t,groups.pressure),authority_laundering:score(t,groups.authority),identity_pressure:score(t,groups.identity),zero_sum_framing:score(t,groups.zero),correction_obstruction:score(t,groups.sealing),actionability_hazard:score(t,groups.hazard),negative_affect:score(t,groups.distress)};const restrictive=Object.entries(s).filter(([k])=>k!=='negative_affect').reduce((a,[,v])=>a+v,0)/8;const level=restrictive<.12?'LOW':restrictive<.3?'MODERATE':'HIGH';repair=`Useful-core question: What limited claim may be worth preserving?\n\nContext questions:\n- What conditions and affected parties are missing?\n- Which source and counterexample can be checked?\n- Who gains money, status, attention, or control?\n- What low-risk reversible action could test the claim?\n- How can an affected person correct, appeal, refund, or exit?`;result.innerHTML=`<div class="notice ${level==='HIGH'?'warn':''}"><b>${level} compact signal load</b><br><span class="muted">This is not a restriction or truth verdict.</span></div>${Object.entries(s).map(([k,v])=>`<div class="signal"><b>${esc(k.replaceAll('_',' '))}${k==='negative_affect'?' (nonrestrictive)':''}</b><div class="bar"><i style="width:${v*100}%"></i></div><span>${v.toFixed(2)}</span></div>`).join('')}<h3>Repair questions</h3><pre style="white-space:pre-wrap">${esc(repair)}</pre>`};
copy.onclick=async()=>{if(!repair)return;await navigator.clipboard.writeText(repair);copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy repair card',1200)};
load();
